
[general]
import = [
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[window]
padding = { x = 8, y = 8 }
opacity = 1

[font]
normal = { family = "FantasqueSansM Nerd Font" }
size = 12

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
bindings = [
  { mouse = "Right", action = "Paste" }
]

[cursor]
style = { shape = "Block", blinking = "Always" }
